name: Build and Release

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build all executables
      run: |
        # Windows
        bun build --compile --target bun-windows-x64 --minify --sourcemap ./index.js --outfile iptveditor4_bypass-win.exe

        # macOS
        bun build --compile --target bun-darwin-x64 --minify --sourcemap ./index.js --outfile iptveditor4_bypass-macos

        # Linux
        bun build --compile --target bun-linux-x64 --minify --sourcemap ./index.js --outfile iptveditor4_bypass-linux

    - name: Generate tag name
      id: tag
      run: |
        TAG_NAME="v$(date +'%y_%m_%d')"
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Generated tag: $TAG_NAME"

    - name: Create and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ steps.tag.outputs.tag_name }}
        git push origin ${{ steps.tag.outputs.tag_name }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.tag_name }}
        files: |
          iptveditor4_bypass-win.exe
          iptveditor4_bypass-macos
          iptveditor4_bypass-linux
        body: |
          ## IPTVEditor Bypass Release ${{ steps.tag.outputs.tag_name }}

          This release contains executables for all platforms:
          - `iptveditor4_bypass-win.exe` - Windows executable
          - `iptveditor4_bypass-macos` - macOS executable
          - `iptveditor4_bypass-linux` - Linux executable

          ### How to use:
          1. Download the appropriate executable for your operating system
          2. Run the executable
          3. The tool will start a local server on port 9710
          4. Your browser will automatically open to https://cloud.iptveditor.com
          5. Use Ctrl+C to stop the server
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}